name: "âš™ï¸ CI feature branch"

on:
  push:
    branches:
      - feature**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  ci-python:
    name: ci-python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: InstalaÃ§Ã£o do Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: InstalaÃ§Ã£o das DependÃªncias
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt
      
      - name: AnÃ¡lise de Linter - flake8
        run:
          flake8 . --ignore E501

      - name: AnÃ¡lise de Docstrings - pydocstyle
        run:
          pydocstyle --match-dir ./app/src/*.py

  open-pr-to-main:
    name: open-pr-to-main
    runs-on: ubuntu-latest
    needs:
      - ci-python

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cria PR para main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref }}
          destination_branch: "main"
          pr_title: "pr(main): ${{ github.ref }} -> main"
          pr_template: ".github/pull_request_template.md"
          pr_assignee: "ThiagoPanini"
          pr_label: "github-bot ðŸ¤–"
          github_token: ${{ secrets.GITHUB_TOKEN }}
