name: "⚙️ CI main"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  ci-python:
    name: ci-python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalação do Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalação das Dependências
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt
      
      - name: Análise de Linter - flake8
        run:
          flake8 . --ignore E501

      - name: Análise de Docstrings - pydocstyle
        run:
          pydocstyle --match-dir ./app/src/*.py
  